#ifndef _OWINDYS_VGA_H_
#define _OWINDYS_VGA_H_

#include "type.h"

#define VGA_COLOR_BLACK 0
#define VGA_COLOR_LOW_BLUE 1
#define VGA_COLOR_LOW_GREEN 2
#define VGA_COLOR_LOW_CYAN 3
#define VGA_COLOR_LOW_RED 4
#define VGA_COLOR_LOW_MAGENTA 5
#define VGA_COLOR_BROWN 6
#define VGA_COLOR_LIGHT_GRAY 7
#define VGA_COLOR_DARK_GRAY 8
#define VGA_COLOR_HIGH_BLUE 9
#define VGA_COLOR_HIGH_GREEN 10
#define VGA_COLOR_HIGH_CYAN 11
#define VGA_COLOR_HIGH_RED 12
#define VGA_COLOR_HIGH_YELLO 14
#define VGA_COLOR_WHITE 15

/*
 * Text Mode
 */
#define VGA_ROWS_NUMBER 25
#define VGA_COLS_NUMBER 80

#endif // VGA_H
